// ISO 3166-1 alpha-2 lowercase codes
export const COUNTRIES = [
  { code: 'al', name: 'Albania' },
  { code: 'am', name: 'Armenia' },
  { code: 'au', name: 'Australia' },
  { code: 'at', name: 'Austria' },
  { code: 'az', name: 'Azerbaiyán' },
  { code: 'be', name: 'Bélgica' },
  { code: 'ba', name: 'Bosnia y Herzegovina' },
  { code: 'bg', name: 'Bulgaria' },
  { code: 'hr', name: 'Croacia' },
  { code: 'cy', name: 'Chipre' },
  { code: 'cz', name: 'República Checa' },
  { code: 'dk', name: 'Dinamarca' },
  { code: 'ee', name: 'Estonia' },
  { code: 'fi', name: 'Finlandia' },
  { code: 'fr', name: 'Francia' },
  { code: 'ge', name: 'Georgia' },
  { code: 'de', name: 'Alemania' },
  { code: 'gr', name: 'Grecia' },
  { code: 'hu', name: 'Hungría' },
  { code: 'is', name: 'Islandia' },
  { code: 'ie', name: 'Irlanda' },
  { code: 'il', name: 'Israel' },
  { code: 'it', name: 'Italia' },
  { code: 'lv', name: 'Letonia' },
  { code: 'lt', name: 'Lituania' },
  { code: 'lu', name: 'Luxemburgo' },
  { code: 'mt', name: 'Malta' },
  { code: 'md', name: 'Moldavia' },
  { code: 'me', name: 'Montenegro' },
  { code: 'nl', name: 'Países Bajos' },
  { code: 'mk', name: 'Macedonia del Norte' },
  { code: 'no', name: 'Noruega' },
  { code: 'pl', name: 'Polonia' },
  { code: 'pt', name: 'Portugal' },
  { code: 'ro', name: 'Rumanía' },
  { code: 'ru', name: 'Rusia' },
  { code: 'sm', name: 'San Marino' },
  { code: 'rs', name: 'Serbia' },
  { code: 'si', name: 'Eslovenia' },
  { code: 'es', name: 'España' },
  { code: 'se', name: 'Suecia' },
  { code: 'ch', name: 'Suiza' },
  { code: 'tr', name: 'Turquía' },
  { code: 'ua', name: 'Ucrania' },
  { code: 'gb', name: 'Reino Unido' },
  // Major world countries
  { code: 'ar', name: 'Argentina' },
  { code: 'br', name: 'Brasil' },
  { code: 'ca', name: 'Canadá' },
  { code: 'cl', name: 'Chile' },
  { code: 'cn', name: 'China' },
  { code: 'co', name: 'Colombia' },
  { code: 'eg', name: 'Egipto' },
  { code: 'in', name: 'India' },
  { code: 'id', name: 'Indonesia' },
  { code: 'jp', name: 'Japón' },
  { code: 'kr', name: 'Corea del Sur' },
  { code: 'mx', name: 'México' },
  { code: 'ma', name: 'Marruecos' },
  { code: 'ng', name: 'Nigeria' },
  { code: 'pe', name: 'Perú' },
  { code: 'ph', name: 'Filipinas' },
  { code: 'za', name: 'Sudáfrica' },
  { code: 'th', name: 'Tailandia' },
  { code: 'tn', name: 'Túnez' },
  { code: 'us', name: 'Estados Unidos' },
  { code: 've', name: 'Venezuela' },
  { code: 'vn', name: 'Vietnam' },
]
